# input: clean rais_crosswalk generated by process_record_linkage.R
# output: rais crosswalk to partisanship data
# intention: create crosswalk between id_employee and electoral title
# to identify what is the electoral title of all employees
source(
    here::here("source/modules/setup_preprocess.R")
)

library(haven)

debug <- FALSE
sample_size <- ifelse(isTRUE(debug), 1e5, Inf)
between <- data.table::between

# ---------------------------------------------------------------------------- #
# extract all id_employees and merge with cpf to generate crosswalk
message("read in data.")

rais_id_employee <- read_dta(
    "/home/BRDATA/RAIS/id/RAIS_employee_identifiers.dta",
    n_max = sample_size
) %>%
    transmute(id_employee, cpf = as.character(cpf)) %>%
    as.data.table()

# first join ids with cpf
filiado_with_cpf <- fread(
  here("data/clean/id/filiado_id_with_cpf.csv.gz"),
  select = c("electoral_title", "cpf")
)

rais_filiado_with_cpf <- unique(filiado_with_cpf)

# join for id_employee
rais_filiado_with_cpf <- rais_filiado_with_cpf[
  rais_id_employee,
  on = "cpf"
]

level <- c("state", "mun")

for (i in level) {
  rais_filiado_table <- fread(
    here(
        sprintf("data/clean/id/rais_filiado_crosswalk_%s.csv", level[i])
    )
  )

  rais_filiado_table[, cpf := as.double(cpf)]

  message("merge rais_filiado_table with id_employees")
  rais_filiado_table[
    as.data.table(rais_id_employee),
    id_employee := i.id_employee,
    on = "cpf"
  ]

  rais_filiado_table %>%
    setkey(id_employee)

  message("check if there are duplicated titles per id_employee")
  rais_multiple_titles <- rais_filiado_table[
    !is.na(id_employee),
    .(count_titles = uniqueN(electoral_title), count_cpf = uniqueN(cpf)),
    by = id_employee
  ]

  defective_titles <- nrow(rais_multiple_titles[count_titles > 1])
  defective_cpf <- nrow(rais_multiple_titles[count_cpf > 1])

  message(
    "there are ",
    defective_titles, "entries with multiple titles and ",
    defective_cpf, "entries with multiple cpfs for id_employee"
  )

  rais_filiado_table %>%
    select(
        id_employee,
        cpf,
        electoral_title
    ) %>%
    fwrite(
        here(
            sprintf("data/clean/id/rais_id_to_filiado_hash_%s.csv", level[i])
        )
    )
}


message("generate rais id_employee to electoral title table...complete!")