# input: clean rais_crosswalk generated by process_record_linkage.R
# output: rais crosswalk to partisanship data
# intention: create crosswalk between id_employee and electoral title
# to identify what is the electoral title of all employees
source(
    here::here("source/modules/setup_preprocess.R")
)

library(haven)

debug <- FALSE
sample_size <- ifelse(isTRUE(debug), 1e5, Inf)
between <- data.table::between

# ---------------------------------------------------------------------------- #
# extract all id_employees and merge with cpf to generate crosswalk
message("read in data.")

rais_id_employee <- read_dta(
    "/home/BRDATA/RAIS/id/RAIS_employee_identifiers.dta",
    col_select = c(id_employee, cpf),
    n_max = sample_size
) %>%
    as.data.table()

# drop NA
rais_id_employee <- na.omit(rais_id_employee)

setkey(rais_id_employee, cpf)

# first join ids with cpf
filiado_with_cpf <- fread(
  here("data/clean/id/filiado_id_with_cpf.csv.gz"),
  select = c("electoral_title", "cpf")
)

# drop NA
filiado_with_cpf <- na.omit(filiado_with_cpf)

rais_filiado_with_cpf <- unique(filiado_with_cpf)

rais_filiado_with_cpf[, cpf := as.double(cpf)]

setkey(rais_filiado_with_cpf, cpf)

# join for id_employee
rais_filiado_with_cpf <- rais_filiado_with_cpf[
  rais_id_employee,
  .(electoral_title, id_employee),
  nomatch = 0
]

level <- c("state", "mun")

for (i in seq_along(level)) {
  rais_filiado_table <- fread(
    here(
        sprintf("data/clean/id/rais_filiado_crosswalk_%s.csv", level[i])
    ),
    select = c("cpf", "electoral_title")
  )

  nrow_original <- nrow(rais_filiado_table)

  # drop NA
  rais_filiado_table <- na.omit(rais_filiado_table)

  message(
    "we drop ", nrow_original - nrow(rais_filiado_table), "observations."
  )

  rais_filiado_table[, cpf := as.double(cpf)]

  message("merge rais_filiado_table with id_employees")
  setkey(rais_filiado_table, cpf)
  
  rais_filiado_table_join <- rais_filiado_table[
    rais_id_employee,
    nomatch = 0
  ]

  rais_filiado_table_join %>%
    setkey(id_employee)

  message("check if there are duplicated titles per id_employee")
  rais_multiple_titles <- rais_filiado_table_join[
    !is.na(id_employee),
    .(count_titles = uniqueN(electoral_title), count_cpf = uniqueN(cpf)),
    by = id_employee
  ]

  defective_titles <- nrow(rais_multiple_titles[count_titles > 1])
  defective_cpf <- nrow(rais_multiple_titles[count_cpf > 1])

  message(
    "there are ",
    defective_titles, " entries with multiple titles and ",
    defective_cpf, " entries with multiple cpfs for id_employee"
  )

  rais_filiado_table_join %>%
    select(
        id_employee,
        electoral_title
    ) %>%
    bind_rows(
      rais_filiado_with_cpf
    ) %>%
    fwrite(
        here(
            sprintf("data/clean/id/rais_id_to_filiado_hash_%s.csv", level[i])
        )
    )
}

message("generate rais id_employee to electoral title table...complete!")