# input: clean rais_crosswalk generated by process_record_linkage.R
# output: rais crosswalk to partisanship data
# intention: create crosswalk between id_employee and electoral title
# to identify what is the electoral title of all employees
source(
    here::here("source/modules/setup_preprocess.R")
)

library(haven)

debug <- FALSE
sample_size <- ifelse(isTRUE(debug), 1e5, Inf)
between <- data.table::between

# ---------------------------------------------------------------------------- #
# extract all id_employees and merge with cpf to generate crosswalk
message("read in data.")

rais_id_employee <- read_dta(
    "/home/BRDATA/RAIS/id/RAIS_employee_identifiers.dta",
    n_max = sample_size
) %>%
    select(id_employee, cpf)

rais_hash_table <- fread(
    here("data/clean/id/rais_filiado_crosswalk_unique.csv")
)

rais_hash_table[, cpf := as.double(cpf)]

message("merge rais_hash_table with id_employees")
rais_hash_table[
    as.data.table(rais_id_employee),
    id_employee := i.id_employee,
    on = "cpf"
]

rais_hash_table %>%
    setkey(id_employee)

message("check if there are duplicated titles per id_employee")
rais_multiple_titles <- rais_hash_table[
    !is.na(id_employee),
    .(count_titles = uniqueN(electoral_title), count_cpf = uniqueN(cpf)),
    by = id_employee
]

defective_titles <- nrow(rais_multiple_titles[count_titles > 1])
defective_cpf <- nrow(rais_multiple_titles[count_cpf > 1])
message(
    "there are ",
    defective_titles, "entries with multiple titles and ",
    defective_cpf, "entries with multiple cpfs for id_employee"
)

rais_hash_table %>%
    select(
        id_employee,
        cpf,
        electoral_title
    ) %>%
    fwrite(
        here("data/clean/id/rais_id_to_filiado_hash.csv")
    )

message("generate rais id_employee to electoral title table...complete!")