# input: record links generated by create_record_linkage.R
# output: unified record links into a single database
# intention: create crosswalk between cpf and electoral title
# to identify what is the electoral title of all employees
source(
    here::here("source/modules/setup_preprocess.R")
)

debug <- FALSE
sample_size <- ifelse(isTRUE(debug), 1e5, Inf)
between <- data.table::between

rais_hash <- fread(
    here("data/clean/id/rais_filiado_crosswalk.csv")
)

rais_hash <- sample_frac(rais_hash, 0.1) %>%
    setkey(cpf)

rais_diagnostics <- fread(
    here("data/clean/id/rais_filiado_linkage_diagnostics.csv")
)

# what are the problematic entries?
# 1) different electoral titles for the same cpf
# 2) duplicated entries
cpf_multiple_entries <- rais_hash[, .(n = .N), by = cpf][
    n > 1
]

rais_hash_multiple_entries <- rais_hash[
    cpf_multiple_entries,
    on = "cpf",
    all = FALSE
]

# different electoral titles
rais_hash_multiple_names <- rais_hash_multiple_entries[
    ,
    .(name, electoral_title, count_names = uniqueN(name)),
    by = cpf
][
    count_names > 1
]

rais_hash_multiple_electoral_titles <- rais_hash_multiple_entries[
    ,
    .(name, electoral_title, count = uniqueN(electoral_title)),
    by = cpf
][
    count > 1
]

rais_hash_multiple_names[cpf %in% sample(rais_hash_multiple_entries[["cpf"]], 5)]