# input: record links generated by create_record_linkage.R
# output: unified record links into a single database
# intention: create crosswalk between cpf and electoral title
# to identify what is the electoral title of all employees
source(
    here::here("source/modules/setup_preprocess.R")
)

debug <- FALSE
between <- data.table::between

# ---------------------------------------------------------------------------- #
rais_hash_file <- here("data/clean/id/rais_filiado_crosswalk.csv") 

if (!isTRUE(debug)) {
    rais_hash_file <- str_replace(rais_file, ".csv$", "_sample.csv")
}

rais_hash <- fread(rais_file)

rais_hash <- rais_hash %>%
    setkey(name)

rais_hash_diagnostics <- rais_hash[
    ,
    .(
        count_title = uniqueN(electoral_title),
        count_cpf = uniqueN(cpf)
    ),
    by = name
]

names_with_multiple_cpfs <- rais_hash_diagnostics[count_cpf > 1, .(name)]

rais_hash[!names_with_multiple_cpfs, on = "name"]