# input: record links generated by create_record_linkage.R
# output: unified record links into a single database
# intention: create crosswalk between cpf and electoral title
# to identify what is the electoral title of all employees
source(
    here::here("source/modules/setup_preprocess.R")
)

debug <- FALSE
between <- data.table::between
sample_size <- Inf

# ---------------------------------------------------------------------------- #
message("read in data.")

rais_hash_file <- here("data/clean/id/rais_filiado_crosswalk.csv") 

if (isTRUE(debug)) {
    rais_hash_file <- str_replace(rais_hash_file, ".csv$", "_sample.csv")
}

rais_hash <- fread(rais_hash_file)

message("create unique hash table linking cpf to electoral title")
rais_hash <- rais_hash %>%
    setkey(name, cpf, electoral_title)

rais_hash_unique <- unique(
    rais_hash, by = c("name", "cpf", "electoral_title")
)

message("write out table.")
rais_hash_unique %>%
    select(
        name, cpf, electoral_title
    ) %>%
    fwrite(
        here("data/clean/id/rais_filiado_crosswalk_unique.csv")
    )